import React,{useMemo,useRef,useState}from"react";
import html2pdf from"html2pdf.js";
import{BREEDS,DEFAULT_WEIGHT_BY_BREED,URNS,EXTRAS,SERVICES,SIZE_LABEL,COM_PRICE}from"../data";
import CertificateTemplate from"./CertificateTemplate";
const WA_GROUP="https://chat.whatsapp.com/KBc1dBIEJQHCoBTmrG96mi?s=cl&p=a&mlu=4&ilr=4";
const clean=function(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9]+/g,"")};
const digits=function(v){return String(v||"").replace(/\D/g,"")};
export default function Configurator(){
const[step,setStep]=useState(1),[worker,setWorker]=useState(false),[secret,setSecret]=useState([]),[secretAt,setSecretAt]=useState(0);
const[data,setData]=useState({service:"",species:"",otherSpecies:"",breed:"",weight:"",petName:"",age:"",urnId:"",plus:false,huella:false,cert:false,frame:"Sin marco",color:"",ownerName:"",ownerPhone:"",ownerAddress:"",deathDate:"",farewell:"",payment:"No pagado",paymentOther:""});
const certRef=useRef(null);
const selectedUrn=URNS.find(function(u){return u.id===data.urnId}),service=SERVICES.find(function(s){return s.id===data.service});
const species=data.species==="Otro"?(data.otherSpecies||"Otro"):data.species;
const autoWeight=data.breed?(DEFAULT_WEIGHT_BY_BREED[data.breed]||""):"",effectiveWeight=data.weight||autoWeight;
const base=data.service==="comunitaria"?(COM_PRICE[effectiveWeight]||0):(selectedUrn&&selectedUrn.prices[effectiveWeight]||0);
const total=base+(data.plus?500:0)+(data.huella?200:0)+(data.cert?50:0);
const set=function(p){setData(function(d){return Object.assign({},d,p)})};
const activate=function(kind){const now=Date.now(),current=now-secretAt>3000?[]:secret,next=current.concat(kind);if(next.length===3&&next[0]==="nextli"&&next[1]==="nextli"&&next[2]==="personalize"){setWorker(true);setSecret([]);setSecretAt(0);return}if(next.length>=3||(next.indexOf("personalize")>=0&&next.length<3))setSecret([]);else setSecret(next);setSecretAt(now)};
const locate=function(){if(!navigator.geolocation){alert("Tu navegador no soporta GPS. Escribe la dirección manualmente.");return}navigator.geolocation.getCurrentPosition(async function(pos){const lat=pos.coords.latitude,lon=pos.coords.longitude;set({ownerAddress:"Ubicación GPS: "+lat.toFixed(6)+", "+lon.toFixed(6)});try{const r=await fetch("https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat="+lat+"&lon="+lon+"&accept-language=es");if(r.ok){const j=await r.json();if(j.display_name)set({ownerAddress:j.display_name})}}catch(e){}},function(){alert("No fue posible obtener la ubicación. Puedes escribir la dirección manualmente.")},{enableHighAccuracy:true,timeout:10000})};
const onBreed=function(b){set({breed:b,weight:DEFAULT_WEIGHT_BY_BREED[b]||""})};
const message=useMemo(function(){return[
"🐾 NEXTLI · Solicitud de despedida","Servicio: "+(service?service.name:"No seleccionado"),"Urna: "+(selectedUrn?selectedUrn.name:"Sin urna"),"Tamaño/peso: "+(SIZE_LABEL[effectiveWeight]||effectiveWeight||"No indicado"),"Especie: "+(species||"No indicada"),"Raza: "+(data.breed||"No indicada"),"Mascota: "+(data.petName||"No indicada"),"Edad: "+(data.age||"No indicada"),"Extras: "+([data.plus&&"Homenaje completo (+$500)",data.huella&&"Huella con pelo (+$200)",data.cert&&"Certificado físico adicional (+$50)"].filter(Boolean).join(", ")||"Ninguno"),data.plus?"Marco: "+data.frame+"; Vinilo: "+(data.color||"No indicado"):"","Tutor: "+(data.ownerName||"No indicado"),"Teléfono: "+(data.ownerPhone||"No indicado"),"Dirección: "+(data.ownerAddress||"No indicada"),"Fecha de defunción: "+(data.deathDate||"No indicada"),data.farewell?"Frase: "+data.farewell:"",worker?"Estado del pago: "+(data.payment==="Otro"?"Otro — $"+(data.paymentOther||"0")+" MXN":data.payment):"","Total estimado: $"+total.toLocaleString("es-MX")+" MXN"
].filter(Boolean).join("\n")},[service,selectedUrn,effectiveWeight,species,data,worker,total]);
const generatePdf=async function(){if(!certRef.current)return;const a=clean(data.petName)||"Cremacion",b=clean(data.ownerName)||"Nextli",filename="Certificado-"+a+"-"+b+".pdf";await html2pdf().set({margin:0,filename:filename,image:{type:"jpeg",quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:"#fbf7ee"},jsPDF:{unit:"mm",format:"a4",orientation:"portrait"}}).from(certRef.current).save()};
const sendClient=function(){const phone=digits(data.ownerPhone);if(!phone){alert("Escribe el teléfono del cliente antes de enviar.");return}generatePdf();window.open("https://wa.me/"+(phone.indexOf("52")===0?phone:"52"+phone)+"?text="+encodeURIComponent(message),"_blank","noopener,noreferrer")};
const sendGroup=async function(){try{await navigator.clipboard.writeText(message)}catch(e){}generatePdf();window.open(WA_GROUP,"_blank","noopener,noreferrer");alert("El resumen quedó copiado al portapapeles. Al abrir el grupo puedes pegarlo y enviarlo.")};
const canNext=step===1?!!data.service:step===2?!!data.species&&!!data.petName:step===3?(data.service==="comunitaria"||!!data.urnId):true;
return <main className="min-h-screen bg-[#0B192C] text-[#F3EFE1]"><header className="sticky top-0 z-30 border-b border-[#d4af37]/10 bg-[#0B192C]/95 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><button onClick={function(){activate("nextli")}} className="font-serif text-2xl tracking-wide">NEXTLI</button><button onClick={function(){activate("personalize")}} className="rounded-full border border-[#d4af37]/60 px-4 py-2 text-sm font-semibold text-[#e7ce83]">Personalizar despedida</button></div></header>
<section className="mx-auto max-w-5xl px-4 py-8"><div className="rounded-[20px] bg-[#FBF7EE] p-5 text-[#241F14] shadow-2xl md:p-10"><div className="mb-8 flex flex-wrap items-center justify-center gap-2">{[1,2,3,4,5].map(function(n){return <React.Fragment key={n}><div className={"flex h-8 w-8 items-center justify-center rounded-full text-xs font-bold "+(step===n?"bg-[#0B192C] text-[#e7ce83]":step>n?"bg-[#d4af37] text-[#0B192C]":"bg-[#e7e0cd] text-[#5b5646]")}>{n}</div>{n<5&&<div className="h-0.5 w-6 bg-[#e7e0cd]"/>}</React.Fragment>})}</div>
{step===1&&<Panel title="Paso 1 · Servicio" note="Elige el servicio que mejor acompañe este momento."><div className="grid gap-4 md:grid-cols-3">{SERVICES.map(function(s){return <button key={s.id} onClick={function(){set({service:s.id,urnId:s.id==="comunitaria"?"":data.urnId})}} className={"rounded-xl border p-5 text-left "+(data.service===s.id?"border-[#d4af37] bg-[#fdf9ee] ring-2 ring-[#d4af37]/15":"border-[#e7e0cd] bg-white hover:border-[#8d783c]")}><h3 className="font-serif text-lg text-[#0B192C]">{s.name}</h3><p className="mt-1 text-sm text-[#5b5646]">{s.description}</p><b className="mt-3 block text-sm text-[#8d783c]">{s.priceLabel}</b></button>})}</div></Panel>}
{step===2&&<Panel title="Paso 2 · Tu compañero" note="La raza ayuda a sugerir automáticamente un rango de peso promedio. Puedes cambiarlo manualmente."><div className="grid gap-4 md:grid-cols-2"><Field label="Nombre de la mascota"><input value={data.petName} onChange={function(e){set({petName:e.target.value})}}/></Field><Field label="Edad"><input value={data.age} onChange={function(e){set({age:e.target.value})}} placeholder="Ej. 8 años"/></Field><Field label="Especie"><select value={data.species} onChange={function(e){set({species:e.target.value,breed:e.target.value==="Otro"?"":data.breed,weight:e.target.value==="Otro"?"":data.weight})}}><option value="">Selecciona…</option><option>Perro</option><option>Gato</option><option>Otro</option></select></Field>{data.species==="Otro"?<Field label="Especie (escribe manualmente)"><input value={data.otherSpecies} onChange={function(e){set({otherSpecies:e.target.value})}}/></Field>:<Field label="Raza"><select value={data.breed} onChange={function(e){onBreed(e.target.value)}} disabled={!data.species}><option value="">Selecciona una raza…</option>{(BREEDS[data.species]||[]).map(function(x){return <option key={x[0]}>{x[0]}</option>})}</select></Field>}<Field label="Peso"><select value={effectiveWeight} onChange={function(e){set({weight:e.target.value})}}><option value="">Selecciona…</option>{Object.entries(SIZE_LABEL).map(function(x){return <option key={x[0]} value={x[0]}>{x[1]}</option>})}</select>{autoWeight&&<div className="mt-1 flex flex-wrap items-center gap-2"><small className="text-xs text-[#5b5646]">El peso promedio de esta raza ha sido sugerido automáticamente.</small><button type="button" onClick={function(){set({weight:""})}} className="text-xs font-semibold text-[#8d783c] underline">Cambiar peso manualmente</button></div>}</Field></div></Panel>}
{step===3&&<Panel title="Paso 3 · Urna y extras" note="Las fotografías y rutas se conservan desde la web de referencia."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.service!=="comunitaria"&&URNS.map(function(u){return <button key={u.id} onClick={function(){set({urnId:u.id})}} className={"overflow-hidden rounded-xl border bg-white text-left "+(data.urnId===u.id?"border-[#d4af37] ring-2 ring-[#d4af37]/15":"border-[#e7e0cd]")}><img src={u.img} className="h-40 w-full object-contain bg-[#FBF7EE] p-3"/><div className="p-3"><b className="font-serif text-[#0B192C]">{u.name}</b><div className="mt-1 text-sm font-bold text-[#8d783c]">{u.prices[effectiveWeight]?"$"+u.prices[effectiveWeight].toLocaleString("es-MX")+" MXN":"Disponible según tamaño"}</div></div></button>})}</div><div className="mt-7 space-y-4">{EXTRAS.map(function(x){return <label key={x.id} className={"flex cursor-pointer gap-4 rounded-2xl border bg-[#fdf9ee] p-4 "+(data[x.id]?"border-[#d4af37] ring-2 ring-[#d4af37]/15":"border-[#e7e0cd]")}><img src={x.img} className="h-20 w-20 rounded-xl bg-white object-contain p-2"/><span className="flex-1"><b className="font-serif text-[#0B192C]">{x.name}</b><small className="mt-1 block text-sm text-[#5b5646]">{x.description}</small><strong className="mt-2 block text-sm text-[#8d783c]">+$ {x.price} MXN</strong></span><input type="checkbox" checked={data[x.id]} onChange={function(e){set({[x.id]:e.target.checked})}} className="mt-2 h-5 w-5 accent-[#d4af37]"/></label>})}</div>{data.plus&&<div className="mt-5 rounded-2xl border border-[#e7e0cd] bg-white p-5"><h3 className="font-serif text-xl text-[#0B192C]">Marcos y Vinilos</h3><div className="mt-4 grid gap-3 sm:grid-cols-3">{["Sin marco","Marco sencillo","Marco doble"].map(function(v){return <button key={v} onClick={function(){set({frame:v})}} className={"rounded-xl border px-4 py-3 text-sm "+(data.frame===v?"border-[#d4af37] bg-[#fdf9ee]":"border-[#e7e0cd]")}>{v}</button>})}</div><div className="mt-4 flex flex-wrap gap-2">{["Plateado","Blanco","Negro","Dorado"].map(function(v){return <button key={v} onClick={function(){set({color:v})}} className={"rounded-full border px-4 py-2 text-sm "+(data.color===v?"border-[#d4af37] bg-[#0B192C] text-[#e7ce83]":"border-[#e2dac2]")}>{v}</button>})}</div></div>}</Panel>}
{step===4&&<Panel title="Paso 4 · Datos y despedida" note="La ubicación puede obtenerse por GPS o escribirse manualmente."><div className="grid gap-4 md:grid-cols-2"><Field label="Nombre del tutor(a)"><input value={data.ownerName} onChange={function(e){set({ownerName:e.target.value})}}/></Field><Field label="Teléfono de contacto"><input value={data.ownerPhone} onChange={function(e){set({ownerPhone:e.target.value})}} placeholder="10 dígitos"/></Field><Field label="Dirección de recolección / entrega"><input value={data.ownerAddress} onChange={function(e){set({ownerAddress:e.target.value})}}/><button type="button" onClick={locate} className="mt-2 w-fit rounded-full border border-[#e2dac2] px-4 py-2 text-xs font-semibold text-[#0B192C]">📍 Obtener ubicación actual por GPS</button><small className="text-xs text-[#5b5646]">También puedes escribir la dirección manualmente.</small></Field><Field label="Fecha de defunción"><input type="date" value={data.deathDate} onChange={function(e){set({deathDate:e.target.value})}}/></Field>{worker&&<Field label="Estado del Pago"><select value={data.payment} onChange={function(e){set({payment:e.target.value})}}><option>No pagado</option><option>Pago liquidado</option><option>Pago del 50%</option><option>Otro</option></select>{data.payment==="Otro"&&<input className="mt-2" type="number" min="0" value={data.paymentOther} onChange={function(e){set({paymentOther:e.target.value})}} placeholder="Monto abonado (MXN)"/>}</Field>}</div><Field label="Una frase de despedida (opcional)"><textarea maxLength={220} value={data.farewell} onChange={function(e){set({farewell:e.target.value})}}/></Field>{worker&&<div className="mt-2 rounded-lg bg-[#f3eddd] p-3 text-xs text-[#5b5646]">Modo trabajador activo.</div>}</Panel>}
{step===5&&<Panel title="Paso 5 · Resumen" note="Revisa tu solicitud antes de enviarla."><pre className="whitespace-pre-wrap rounded-xl bg-white p-5 text-sm leading-6 text-[#241f14]">{message}</pre><div className="mt-5 flex flex-wrap gap-3">{!worker?<a className="rounded-full bg-[#d4af37] px-6 py-3 font-semibold text-[#0B192C]" target="_blank" rel="noreferrer" href={"https://wa.me/525521889698?text="+encodeURIComponent(message)}>Enviar por WhatsApp</a>:<><button onClick={sendGroup} className="rounded-full bg-[#0B192C] px-5 py-3 font-semibold text-[#e7ce83]">Mandar WhatsApp a Grupo Nextli</button><button onClick={sendClient} className="rounded-full bg-[#d4af37] px-5 py-3 font-semibold text-[#0B192C]">Enviar WhatsApp al Cliente</button><button onClick={generatePdf} className="rounded-full border border-[#8d783c] px-5 py-3 font-semibold text-[#0B192C]">Descargar Certificado PDF</button></>}</div></Panel>}
<div className="mt-8 flex justify-between gap-3 border-t border-[#e7e0cd] pt-5">{step>1?<button onClick={function(){setStep(step-1)}} className="rounded-full border border-[#0B192C]/20 px-5 py-3 font-semibold">Atrás</button>:<span/>}{step<5?<button disabled={!canNext} onClick={function(){setStep(step+1)}} className="rounded-full bg-[#0B192C] px-6 py-3 font-semibold text-[#e7ce83] disabled:opacity-40">{step===4?"Ver resumen":"Continuar"}</button>:<button onClick={function(){setStep(1)}} className="rounded-full border border-[#0B192C]/20 px-5 py-3 font-semibold">Nueva despedida</button>}</div><div className="mt-4 text-right text-sm font-bold text-[#8d783c]">Total: $"+total.toLocaleString("es-MX")+" MXN</div></div></section><div className="fixed -left-[10000px] top-0"><CertificateTemplate ref={certRef} data={Object.assign({},data,{species:species,serviceName:service&&service.name})}/></div></main>
}
function Panel({title,note,children}){return <div><h2 className="font-serif text-2xl text-[#0B192C]">{title}</h2><p className="mt-3 rounded-lg border-l-4 border-[#d4af37] bg-white p-4 text-sm leading-6 text-[#5b5646]">{note}</p>{children}</div>}
function Field({label,children}){return <label className="flex flex-col gap-2 text-sm font-semibold text-[#0B192C]">{label}{children}</label>}